---
functional:
-  Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
-  Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
-  Пользователь должен иметь возможность фильтровать товары
-  Пользователь должен иметь возможность искать товары по ключевому слову или категории
-  
non-functional:
-  Сайт должен быть доступен на различных устройствах
-  Важно, чтобы сайт мог обрабатывать большое количество трафика
-  Сайт нужно протестировать на совместимость с последними версиями браузеров
-  Сайт должен иметь мобильную версию
-  Сайт должен быть безопасным и защищать данные пользователя
-  Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit:
-  Сайт должен иметь различные шрифты для удобства ориентации в товарах
-  Сайт должен иметь качественные изображения без искажения 
-  Сайт должен иметь единый формат изображений в списке товаров
-  Сайт должен конвертировать валюту для удобства покупки из разных стран
-  Сайт должен иметь удобные кнопки навигации
