---
functional:
-  Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
-  Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
-  Пользователь должен иметь возможность фильтровать товары
-  Пользователь должен иметь возможность искать товары по ключевому слову или категории 
non-functional:
-  Сайт должен быть доступен на различных устройствах
-  Важно, чтобы сайт мог обрабатывать большое количество трафика
-  Сайт нужно протестировать на совместимость с последними версиями браузеров
-  Сайт должен иметь мобильную версию
-  Сайт должен быть безопасным и защищать данные пользователя
-  Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit:
-  Сайт должен иметь единый стиль написания названия и описания товаров
-  Должен осуществляться переход по ссылке на категорию товара в карточке товара
-  Должна быть возможность выбора любого изображения товара в карточке товара
-  После покупки товара на главной странице должен быть показан актуальный остаток товара
-  Сайт при выборе языка должен переводить все тексты на выбранный язык
-  При нажатии на кнопку "Магазин" сайт переходит на главную страницу магазина
-  Возможность сбросить категории товаров в фильтре без перезагрузки страницы
-  В выборе языка должны быть иконки флагов страны данного языка
-  Кнопка "Hexlet Store" в заголовке должна возвращать сайт на главную страницу
